#!/usr/bin/env python3
"""
Generate a simple traceability matrix:
- REQ -> design files that reference it
- REQ -> test files that reference it
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]
# Allow running via `python tools/traceability/generate_matrix.py` from anywhere.
sys.path.insert(0, str(_REPO_ROOT))

from tools.traceability.check_traceability import build_report  # noqa: E402


def _rel(p: Path, base: Path) -> str:
    try:
        return str(p.relative_to(base))
    except ValueError:
        return str(p)


def _format_paths(paths: set[Path], *, base: Path) -> str:
    if not paths:
        return ""
    return ", ".join(f"`{_rel(p, base)}`" for p in sorted(paths))


def render_markdown(*, docs_dir: Path, tests_dir: Path) -> str:
    report = build_report(docs_dir=docs_dir, tests_dir=tests_dir)

    lines: list[str] = []
    lines.append("# Traceability matrix (generated)")
    lines.append("")
    lines.append("Generated by `tools/traceability/generate_matrix.py`.")
    lines.append("")
    lines.append("| Requirement | Design references | Test references |")
    lines.append("|---|---|---|")

    for req_id in sorted(report.defined_requirements):
        design = _format_paths(report.design_refs.get(req_id, set()), base=docs_dir.parent)
        tests = _format_paths(report.test_refs.get(req_id, set()), base=tests_dir.parent)
        lines.append(f"| `{req_id}` | {design} | {tests} |")

    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Generate a REQ→DES/TEST traceability matrix.")
    parser.add_argument("--docs", type=Path, default=Path("docs"), help="Docs root (default: docs)")
    parser.add_argument(
        "--tests", type=Path, default=Path("tests"), help="Tests root (default: tests)"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Write matrix to this path (Markdown). If omitted, prints to stdout.",
    )
    args = parser.parse_args(argv)

    md = render_markdown(docs_dir=args.docs, tests_dir=args.tests)
    if args.output is None:
        print(md, end="")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(md, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(__import__("sys").argv[1:]))
